### ISSUE TITLE
`Error loading webview` when opening HDF5 file

### ISSUE THREAD

**Issue by loichuder** [silx-kit/vscode-h5web#18] opened 2022-11-22 14:17 UTC
### Describe the bug

Sometimes, when I try to open a HDF5 file, I get this error in VSCode:

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

and the file does not open (I get an empty tab).

### To Reproduce

Hard to say. The error comes and goes :confused: and is not linked to specific files as far as I know.

Closing and re-opening VSCode fixes the problem.

### Context

- OS: Ubuntu 22.04
- VS Code version: 
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-53-generic snap
Sandboxed: No
- Extension version: v0.0.6

**Comment by axelboc** [comment] 2023-09-07 11:29
Closing since it cannot really be solved with the info provided. If anyone manages to reproduce the issue consistently or narrow down the cause, please do re-open.

**Closed by axelboc** 2023-09-07 11:29 UTC
