### ISSUE TITLE
Support viewing h5 files that are written with Pandas

### ISSUE THREAD

**Issue by dflatow** [silx-kit/vscode-h5web#30] opened 2023-09-06 17:39 UTC
### Is your feature request related to a problem?

I'm writing h5 files via pandas (version 2.1.0). Something simple like this:
`df.to_hdf(key=key, path_or_buf=path, append=True)` 

When I go do view the data I get the following:

![image](https://github.com/silx-kit/vscode-h5web/assets/5514147/30c77f92-5c4d-4850-8170-53742a0bcac6)

![image](https://github.com/silx-kit/vscode-h5web/assets/5514147/4b132fb3-4183-455a-8674-a33f43be0687)

### Requested solution or feature

Would be great to be able to visualize the data. I'm not sure if this is a bug or a feature request. 

### Alternatives you've considered

Don't see any alternative VScode pluggins to view h5 files.

**Comment by axelboc** [comment] 2023-09-07 09:09
Hi @dflatow, thanks for the report.

The `Matrix` visualisation is capable of displaying datasets with a `Compound` dtype, as long as every field has a "printable" dtype, which H5Web defines [as the following](https://github.com/silx-kit/h5web/blob/8e8e84caea94ec29859c8f52ae58f69e13550051/packages/shared/src/guards.ts#L35-L42): integer, unsigned integer, float, string, boolean, complex. For an demonstration, take a look at dataset `/nD_datasets/oneD_compound` on [H5Web's demo site](https://h5web.panosc.eu/mock).

If any of the fields is not printable (which seems to be the case here), H5Web falls back to the "Raw" visualisation, which attempts to serialize the dataset to JSON. Since the dataset seems to contain big integers, `JSON.stringify()` throws an error:

![image](https://github.com/silx-kit/vscode-h5web/assets/2936402/412a6053-d227-432b-ae42-a2a24898c1e9)

Could you please share the raw type of the dataset (click on "Inspect" on the row labelled "Raw")? Or even better,  could you share an example file?

**Comment by peku33** [comment] 2023-10-03 20:04
I found the same issue. It generally fails if `format='table'` is passed to `pandas.HDFStore.put()`

**Comment by loichuder** [comment] 2023-10-04 06:36
@axelboc The issue derives from https://github.com/silx-kit/vscode-h5web/issues/15: some part of the compound dataset value has `BigInt` that are not serializable. 

We solved #15 by converting `BigInt` to regular integers when encountering datasets with integer dtypes but forgot that these `BigInt` can show up in `Compound` datasets, such as the ones generated by `pandas`.

It can be reproduced with a file holding a single compound dataset with a field with `int64` (in this case `age`):
```python
with h5py.File(...) as h5file:
      # From https://numpy.org/doc/stable/user/basics.rec.html
      h5file.create_dataset(
          "dogs",
          data=np.array(
              [("Rex", 9, 81.0), ("Fido", 3, 27.0)],
              dtype=[("name", "S10"), ("age", "i8"), ("weight", "f4")],
          ),
      )
```

**Comment by loichuder** [comment] 2023-10-04 06:44
In the meantime, it is possible to circumvent the issue when saving with `pandas`: removing `append=True` from the call to `to_hdf` saves the columns as separate datasets rather than in a single compound dataset. 

H5Web should not have issues viewing these separate datasets.

**Comment by axelboc** [comment] 2023-10-06 06:36
Should be fixed in the next release. I'll try to get it out asap.

**Closed** 2023-10-06 06:36 UTC
